package com.example.baekjoon;

import static org.junit.jupiter.api.Assertions.*;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.PrintStream;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;

class q1285Test {

  private static OutputStream out;
  private static InputStream in;

  @BeforeAll
  static void setting(){
    out = new ByteArrayOutputStream();
    System.setOut(new PrintStream(out));
  }

  private void testCorrect(String input, String output) throws IOException {
    out = new ByteArrayOutputStream();
    System.setOut(new PrintStream(out));
    in = new ByteArrayInputStream(input.getBytes());
    System.setIn(in);

    q1285 q = new q1285();
    q.run();

    assertEquals(output,out.toString());
  }


  @Test
  void main() throws IOException {
    testCorrect("6\n"
        + "HHTTHH\n"
        + "TTHHTH\n"
        + "TTTHTH\n"
        + "HTTTTT\n"
        + "TTTHHT\n"
        + "TTHTTT", "9");
    testCorrect("8\n"
        + "THTHHHTH\n"
        + "TTHTHHTH\n"
        + "HHHTHHHH\n"
        + "TTTHHTHH\n"
        + "HHHTHHHH\n"
        + "TTHTHTHT\n"
        + "HTHHTTHT\n"
        + "HHHTHTTH", "15");
    testCorrect("9\n"
        + "HTHTHHTTT\n"
        + "TTTHTTHHT\n"
        + "HHTTTHTHH\n"
        + "HTHTHTHHH\n"
        + "THHHHHHTH\n"
        + "HHTTHTHHT\n"
        + "THTHTHTHT\n"
        + "THHTHTHTH\n"
        + "HHHHTHHHT", "23");
    testCorrect("20\n"
        + "THHTHTTHTTHTHHHTTHTH\n"
        + "TTTTHHTTHTTTTTHTHTTT\n"
        + "TTHHTHTHHTHTHHHTTHTT\n"
        + "THTHTTHHHTTTHHHHTTTT\n"
        + "HHTHHTHTTTHHHTHTTTHT\n"
        + "HTHHHTTHHHTHTTTTTHTT\n"
        + "THTTHTTTTTTHHHHTHHHH\n"
        + "HTTHHHTHTTHTHTTHHTTT\n"
        + "HHTHHTTTTTHHTHHTTHHH\n"
        + "HHHTTHTHHTTTHHTHHHHH\n"
        + "HHTTTHTTTTHHHHHTTHHH\n"
        + "HTHTHTHHHTTTHHHHHHTT\n"
        + "HTHTTHTTHHTHHHTTTHTH\n"
        + "TTTTTHHTTHTHHTHTHHTT\n"
        + "TTTTTHHTHTTTTHTHHHHT\n"
        + "HHHHTTTTTHHTHTHHTTHT\n"
        + "HTTHHHHTTHTTTTTHTHTH\n"
        + "HTTHHHTTHTHTTHHHHHTT\n"
        + "HHHTHTHTTHTHTTHTTHHH\n"
        + "HTTTHHHHTHHHTHHHTHHT", "137");
    testCorrect("17\n"
        + "HHHHHHTHTTTTTTHHH\n"
        + "THTHTHTTHTHTTHTHT\n"
        + "HTHHHTTTTTHTTHHHH\n"
        + "TTHTHHHHHHTHHTTTT\n"
        + "TTTTTHHTTHHTHTHTT\n"
        + "TTHHHTHHHHHTHHHTT\n"
        + "HHHHTHHHTHTTTTTHH\n"
        + "THTHHTHHHTHTHTTHH\n"
        + "HTHTHHHTHTHHHTTTH\n"
        + "THTHTHHHHTHHHTHHT\n"
        + "TTHTHHTHTHTHTTHTT\n"
        + "HTHTHTTTTHHTHTHHT\n"
        + "TTTTTHHHHTHTTHHHT\n"
        + "HTTTTTTTHHHHHTHHT\n"
        + "HTHTHHHHHHTHTTTHT\n"
        + "THHHHTTHTHTTTTHHT\n"
        + "HHHHHTHHTHTTHHHHT", "94");
    testCorrect("20\n"
        + "HHHTHTHHTTTTTTHHHTTH\n"
        + "TTHHHTTHHTHHTTTTHHTH\n"
        + "THHHTTTHTTHHTHTTTTTH\n"
        + "THHHHHTHTTTHHHHTHTTH\n"
        + "THHHTTTHHTTHHHTHTHHH\n"
        + "THTHHHHTHHTHHTHTTHTT\n"
        + "THHHHTHTHTTTTHHTTHTT\n"
        + "HHTTHHTTTHHTHHHTTTHH\n"
        + "TTHHTTTTTHHHTTHHTTHH\n"
        + "TTTTTHHHHTTTHTTHTTTH\n"
        + "HTHHTHHHTTTTTTHTTHHH\n"
        + "TTHHHTHHHTTHTTTHTTHH\n"
        + "THTTTTHHTHHTHHTHTTHT\n"
        + "HTHHHHTTTTTHTTTTHHTT\n"
        + "TTHTTHTTHHTTHTTHHTHT\n"
        + "THTHHHHTHHTHHTHTHTHT\n"
        + "THHHHHTHHTTHTHHTTTTH\n"
        + "HTTTHHTHTHTHTHTTTTHT\n"
        + "HHHTHHTHHTTTTTHTTTTT\n"
        + "HTTTHHTTTHTHHHTTHHHT", "133");
    testCorrect("13\n"
        + "TTHTHTHTTHHTH\n"
        + "THHTHTHHHHTTH\n"
        + "THHTHHHTTTTTH\n"
        + "THHTTTHHTHTHT\n"
        + "HHTHHHTHTTHTH\n"
        + "TTTTHHTHTTTHH\n"
        + "THHHHTHTHTHHH\n"
        + "HTHHTTTTHHHHH\n"
        + "HTTHHTTHHTTTT\n"
        + "HTTTHHTTHHHHT\n"
        + "THTHHTTHTTHTT\n"
        + "THHTHTTHHTTTT\n"
        + "HTHTHTTTTHTTT", "53");
    testCorrect("16\n"
        + "TTTHHTTTTTTTHTHH\n"
        + "HTHTHHTHHHHTTHTT\n"
        + "HTHHHHHTTTHHHTTT\n"
        + "HTHTTHTHTTTTHTHH\n"
        + "THTHTTTTTTHTHTTT\n"
        + "THTHTTHTHHTHTHHT\n"
        + "HTHTHHTTHTHTHHTH\n"
        + "TTTHHHTHTTHHHHHT\n"
        + "THTTTTTHHHTTHHTH\n"
        + "HTHHTHHTHTTTHTHT\n"
        + "THTTHTTHHTTHHHHT\n"
        + "HTTHTHTHTHTHTHTT\n"
        + "HTTTTHTTHTTHTHHT\n"
        + "HHTHHTTTHTHHTHHT\n"
        + "HTHTTTHTHTHHHTHH\n"
        + "TTTHHTTHTHTTTTTH", "85");
    testCorrect("18\n"
        + "HHTHHHTHHHTTHTTHHT\n"
        + "HHHTHTHTTTTHTHTHTT\n"
        + "THHHTTHTTTHTHTHTHT\n"
        + "HHHTTHTTHHTTTTTHTT\n"
        + "HHTHTHTHTHTTHHTTHT\n"
        + "HTTTHTHHHTHHTHTTTT\n"
        + "HTTHTTHHHHHTHTTHTH\n"
        + "HHHTTTHHHTTHTTHTTH\n"
        + "HHTHHTHHHHTHTHHHTH\n"
        + "TTTTTTHHHTTHHHHTHT\n"
        + "HHHTTHTHTHTTTTHHTT\n"
        + "HTTTHTTHTHTTTTTTHT\n"
        + "TTHHTTTHHTTTTHHTTT\n"
        + "HTTTTTHHHTHHTHHHTT\n"
        + "HHHHTTTTTTHHHTHHTH\n"
        + "THHHHHTHTTHTTTHHTT\n"
        + "HTTHHHHHHTTTHTTHTH\n"
        + "TTTTHTTHTTTHTHHTHH", "105");
    testCorrect("13\n"
        + "TTTHHTHTHHTHT\n"
        + "HHHHTHTHHHTTH\n"
        + "TTTTTHTTHTHTH\n"
        + "HHTHTTTHHTTTH\n"
        + "HHHHHHTHTTTTH\n"
        + "TTTTHHTTTTHTH\n"
        + "TTHHTTHHHHHHT\n"
        + "THHHHTTHTHHHH\n"
        + "HTTTHHTTHHHHH\n"
        + "TTTTHTHTTHTHH\n"
        + "TTTHTTTHTHTHH\n"
        + "TTHTTHHTTTTHH\n"
        + "HHTTTTTTTHHTH", "52");
    testCorrect("14\n"
        + "THHHTTHTHHHHHT\n"
        + "HTHTTTTHTTTTHT\n"
        + "THHTHTHHHHTTHT\n"
        + "THHTTHHHTTTHHT\n"
        + "HTHTHHTTHHTTTT\n"
        + "HTHHHTTHTTTHHT\n"
        + "HTHHHTHTHTHTHH\n"
        + "TTTHHHHTTHTTHT\n"
        + "TTHTTTHTTTHHHT\n"
        + "THTTTTTTTTTHHH\n"
        + "HHHHTTHTHHTHHT\n"
        + "HTTHHTTTTHTHTT\n"
        + "THTTHTTHHHHHTH\n"
        + "HHHHTTHHHTTHTT", "61");
    testCorrect("13\n"
        + "TTHTTTHTTHHHH\n"
        + "THTTHHTHTHTTT\n"
        + "THHHTTTTHHHTH\n"
        + "THTHHTTHTTHTH\n"
        + "THTHTTHHTHTHT\n"
        + "THHHTHHTHTTTH\n"
        + "HTHTHHTTHHTTT\n"
        + "HTTHTTHHHTTTH\n"
        + "HHHTTTHHTHHTH\n"
        + "HHHTHHTTHHTHT\n"
        + "TTTTTHHHHTTHH\n"
        + "THHHHHHTHHTHT\n"
        + "TTHTHHHTTTTTT", "52");
    testCorrect("12\n"
        + "TTTTTTHHHHTT\n"
        + "TTTTTHHHHTTH\n"
        + "TTHTTHTHTHTT\n"
        + "HHTTTHHTTHHH\n"
        + "HTHHHHTTTTHT\n"
        + "HHHHHHTHHHHH\n"
        + "TTHTTTTTTHTH\n"
        + "THHTTHHTHHTH\n"
        + "TTHTHTHTHTHT\n"
        + "HHTTTHHHHHHH\n"
        + "HTHHTHTHHTHH\n"
        + "HHHHHTHHHHTT", "44");

    testCorrect("17\n"
        + "HHTTHTTTHHTTHTTTH\n"
        + "HTTTHTTHTHHTHTHHH\n"
        + "TTTHHTTTHTHHTTTTT\n"
        + "HHTTHHHHTHTHTTTTH\n"
        + "HHTHHHTTTTTHHTTHH\n"
        + "HHTTHHHHHHTTHTHHH\n"
        + "TTHHTTHTTTHTTHHTT\n"
        + "HHTHTHHHHTHTHTTTT\n"
        + "HTHHTTHTHTTHTTHTT\n"
        + "HHTTHHHTHTHHHTHTT\n"
        + "THTTHHTTHHHTHTTHH\n"
        + "HHHTHHHHTHTHHHTHT\n"
        + "HTHHHTHTHTHTTHHHH\n"
        + "THTTHHHHTHTHHHHTH\n"
        + "HTTHHHTHHHHTHHTHT\n"
        + "TTHHHTHTTHTTTTTTH\n"
        + "THTTHTHHTTHHHTHHT", "86");
    testCorrect("9\n"
        + "THTTTTHTT\n"
        + "HHTTTHTHH\n"
        + "HHTTHHHTH\n"
        + "THTTHHTTH\n"
        + "TTTTHHHHT\n"
        + "TTHHHHHHT\n"
        + "HTHHTHTTH\n"
        + "HHHHTHHHT\n"
        + "HHHHHTTHH", "23");
    testCorrect("15\n"
        + "TTTHTTTTTTHTTTT\n"
        + "HTTHHHHTTHHTHTT\n"
        + "HTHHTHTHHHTTTHT\n"
        + "TTHTHHTTHTHTTTH\n"
        + "HTTTTTTHTTHTTHH\n"
        + "HHTHHTTHHTTTHTT\n"
        + "TTTTTTHTTHHTTTT\n"
        + "HTHHHHTTHHHTHHT\n"
        + "THHTHTTHHHTTTHH\n"
        + "THTTTTHHHTHHHTT\n"
        + "HTHHHTHTTHHTTTT\n"
        + "HTHTHTTTTHTHTTH\n"
        + "HHTTHHTHHTTTHHH\n"
        + "TTTHTTTTTTTHTTT\n"
        + "HHTTTTTHHHHTTHT", "71");
    testCorrect("9\n"
        + "THTTHTHTT\n"
        + "HTTTHHHHT\n"
        + "HHTHHTTHT\n"
        + "HTHHHHTTT\n"
        + "TTTHTTHTT\n"
        + "THTHTHHHT\n"
        + "HTTHTTHTT\n"
        + "HTTHTHTHT\n"
        + "TTTHTHHHT", "22");
    testCorrect("10\n"
        + "HTTTHHTHHH\n"
        + "TTTHHHHHTH\n"
        + "THHTHHHHHT\n"
        + "HHHHHTTTTT\n"
        + "THHTTHTHTT\n"
        + "THTHHTTTTH\n"
        + "HHHHTTTTTT\n"
        + "HHTTTHTTHT\n"
        + "THHTHHHHTT\n"
        + "HTHHTTHTTT", "26");
    testCorrect("3\n"
        + "HHT\n"
        + "THH\n"
        + "THT", "2");
    testCorrect("17\n"
        + "THHTHHHHHTTTTTTTH\n"
        + "THTHHTHHTHHTTHTHT\n"
        + "HTTTHTTHTTHTTTHTH\n"
        + "HTTTTTTHHTHHHHHHH\n"
        + "HHTHTHHHTTHTTHHHH\n"
        + "HHTHHTHTTHHHTTTTT\n"
        + "HHHTHTHTTHHHTTTTH\n"
        + "HHTHTTTHTHHHTHHHT\n"
        + "TTTTTTTTTTHTHHHHH\n"
        + "THHTHTHTHTHTTTHHT\n"
        + "HHHHTHTHHTHTTHHHH\n"
        + "TTHTHTTTHTTHTHTTH\n"
        + "TTHHTHHHTTHTTTTTT\n"
        + "HTHHHHHHHTTHTTHHH\n"
        + "HHTHTHTTHHTHHHTHH\n"
        + "HHTTTHHHTHHTTTTHH\n"
        + "TTHHHTTTHTTTTHTHT", "93");
    testCorrect("19\n"
        + "HTTHHTHTTHTHHTTHTTH\n"
        + "THHTTTTHTTTTHTTTTHH\n"
        + "THHTHHTHTHTTTTTHHHT\n"
        + "THTHHHTHHHTTTHTHHTH\n"
        + "TTHHHTTHTHHHHTTHTHT\n"
        + "THHHHHHTTHTTHTTHTHH\n"
        + "THHTTHTTTTHTHTTTHTT\n"
        + "TTHHHHHHTHTHHHTTTHH\n"
        + "TTHHHTHTTHHHHTHHTTH\n"
        + "HHTHHTHHHTHTHTTHHTH\n"
        + "HTTTHTTTHTHHHTHTTTT\n"
        + "HHHHHHTTTTTHHHHTHTH\n"
        + "THTHHTTTHHTTHTHTHTT\n"
        + "THHHTHTHTHTHHHTTHHH\n"
        + "THTTTTTHHTHTHTTTTTT\n"
        + "THHTTHHHHHTTHTTTTTT\n"
        + "HTHTHHTTTTTTHHHTTHH\n"
        + "TTTHTHHTHTHHTHTTTTH\n"
        + "HTTHHHTHTHTTHHHTHHT", "120");
  }
}
